name: release
on:
  push:
    branches:
      - 'main'
    paths:
      - 'manifest.json'
  workflow_dispatch:
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get version
        id: version
        run: echo "version=$(jq -r .version manifest.json)" >> $GITHUB_OUTPUT

      - name: inject secrets
        run: |
          sed -e "s/GOOGLE_CLIENT_ID/${{ secrets.GOOGLE_CLIENT_ID }}/g" \
              -e "s/GOOGLE_CLIENT_SECRET/${{ secrets.GOOGLE_CLIENT_SECRET }}/g" \
              background/secrets.js.template > background/secrets.js

      - name: install web-ext
        run: npm install -g web-ext

      - name: build
        run: web-ext build --filename=companion-v${{ steps.version.outputs.version }}.xpi

      - name: sign extension
        run: |
          web-ext sign \
            --source-dir=. \
            --artifacts-dir=web-ext-artifacts \
            --channel=unlisted \
            --api-key=${{ secrets.AMO_JWT_ISSUER }} \
            --api-secret=${{ secrets.AMO_JWT_SECRET }} \
            --timeout=900000

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          files: web-ext-artifacts/companion-v${{ steps.version.outputs.version }}.xpi
